### ISSUE TITLE
Do not confirm app close

### ISSUE THREAD

**Issue by kpengboy** [szafir1100/notepad#13]
Having a close app confirmation box that pops up when you hit the back button is a bit of an annoyance. (No other app does that.) Instead, everything should be saved automatically, so there won't be any need to ask the user whether they want to exit.

The confirmation box is ineffective anyway because there are other ways for the app to be closed besides by pressing the back button.

**Comment by szafir1100** [comment]
Thanks for feedback,
I'm teaching kiteboarding today, but I'll take a look at this tomorrow!
Cheers from Poland!
Tomek

**Comment by szafir1100** [comment]
@kpengboy 
Done at: https://github.com/szafir1100/drawable-notepad/commit/a7e960ae4d49460f4402dfac071d5250158bc761
Thanks for feedback!
