### ISSUE TITLE
Add a Title Field

### ISSUE THREAD

**Issue by stollr** [szafir1100/notepad#20]
Thanks for your app. It looks nice and it's great that it is available via F-Droid ;-)

Currently it is not possible to add a title (or summery) to the note. This would be a nice feature. Because the numberation on the main screen is not very helpful.
This field could be made optional. So that people who dont need them have no disadvantages.

**Comment by tmarzeion** [comment]
Fixed by @koroshiya at https://github.com/tmarzeion/drawable-notepad/pull/21
