### ISSUE TITLE
Crash if no text

### ISSUE THREAD

**Issue by Nico207** [szafir1100/notepad#4]
Hi, 
I have found a little bug... 
- open a new note
- draw some lines
- save and close the note without writing text
- open this note : the app crash

**Comment by szafir1100** [comment]
Hey :)

Thats weird, I've fixed this bug some time ago.
Could You tell me whats your telephone model so I will be able to debug it
on emulated machine?

Thanks for feedback!
Tomek

2016-03-08 22:56 GMT+01:00 Nico207[FR] notifications@github.com:

**Comment by Nico207** [comment]
Here is :
Samsung Galaxy S4 mini (GT-i9195)
on Cyanogenmod 11 (Android 4.4.4)

**Comment by szafir1100** [comment]
That may be caused because of CM, I'll check it out :)

**Comment by szafir1100** [comment]
Fixed at: https://github.com/szafir1100/drawable-notepad/commit/6d9dde3bbf8bee63c2bb82e31edfff21d6c4eb0e
Thanks for reporting this issue,
Tomek
